[general]
live_config_reload = true

[window]
opacity = 0.9

[font]
size = 14.0

[font.offset]
x = 0
y = -1

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
