[general]
live_config_reload = true

[window]
opacity = 0.9

[font]
size = 14.0

[font.offset]
x = 0
y = -1

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[terminal]
osc52 = "CopyPaste"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"

# C-; as explicit CSI u â€” needed because tmux doesn't support kitty keyboard protocol
[[keyboard.bindings]]
key = "Semicolon"
mods = "Control"
chars = "\u001b[59;5u"
